package cn.com.dhcc.traps.models;

// Generated 2018-1-11 15:27:54 by Hibernate Tools 4.3.1

/**
 * AlarmId generated by hbm2java
 */
public class AlarmId implements java.io.Serializable {

	private long almSn;
	private int count;

	public AlarmId() {
	}

	/**
	 * @return the almSn
	 */
	public long getAlmSn() {
		return almSn;
	}

	/**
	 * @param almSn the almSn to set
	 */
	public void setAlmSn(long almSn) {
		this.almSn = almSn;
	}

	/**
	 * @return the count
	 */
	public int getCount() {
		return count;
	}

	/**
	 * @param count the count to set
	 */
	public void setCount(int count) {
		this.count = count;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (almSn ^ (almSn >>> 32));
		result = prime * result + count;
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AlarmId other = (AlarmId) obj;
		if (almSn != other.almSn)
			return false;
		if (count != other.count)
			return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "AlarmId [almSn=" + almSn + ", count=" + count + "]";
	}
	
}
