package cn.com.dhcc.traps.models;

// Generated 2018-1-11 15:27:54 by Hibernate Tools 4.3.1

/**
 * Alarm generated by hbm2java
 */
public class Alarm implements java.io.Serializable {

	private CmoType cmoType;
	/**
	 * @return the cmoType
	 */
	public CmoType getCmoType() {
		return cmoType;
	}

	/**
	 * @param cmoType the cmoType to set
	 */
	public void setCmoType(CmoType cmoType) {
		this.cmoType = cmoType;
	}

	private AlarmId id;
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Alarm [cmoType=" + cmoType + ", id=" + id + ", mosn=" + mosn
				+ ", rmosn=" + rmosn + ", pmosn=" + pmosn + ", motype="
				+ motype + ", alarmKpi=" + alarmKpi + ", cause=" + cause
				+ ", almType=" + almType + ", suppressed=" + suppressed
				+ ", addInfo=" + addInfo + ", severity=" + severity
				+ ", status=" + status + ", trend=" + trend + ", occurTime="
				+ occurTime + ", lastTime=" + lastTime + ", opStatus="
				+ opStatus + ", detail=" + detail + ", originSn=" + originSn
				+ ", originInfo=" + originInfo + ", upgradeCount="
				+ upgradeCount + ", originSeverity=" + originSeverity
				+ ", clearTime=" + clearTime + ", confirmTime=" + confirmTime
				+ ", confirmUserId=" + confirmUserId + ", delTime=" + delTime
				+ ", delUserId=" + delUserId + ", relatedKpi=" + relatedKpi
				+ ", relatedMosn=" + relatedMosn + ", dataTime=" + dataTime
				+ ", dataValue=" + dataValue + ", moip=" + moip + ", moalias="
				+ moalias + ", causeAlias=" + causeAlias + ", health=" + health
				+ ", isNotify=" + isNotify + ", almLocator=" + almLocator
				+ ", flag=" + flag + ", topMoType=" + topMoType
				+ ", causeWithSeverity=" + causeWithSeverity + "]";
	}

	/**
	 * @return the rmosn
	 */
	public int getRmosn() {
		return rmosn;
	}

	/**
	 * @param rmosn the rmosn to set
	 */
	public void setRmosn(int rmosn) {
		this.rmosn = rmosn;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Alarm other = (Alarm) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	private int mosn;
	private int rmosn;
	private int pmosn;
	private String motype;
	private String alarmKpi;
	private String cause;
	private String almType;
	private Character suppressed;
	private String addInfo;
	private int severity;
	/**
	 * @return the severity
	 */
	public int getSeverity() {
		return severity;
	}

	/**
	 * @param severity the severity to set
	 */
	public void setSeverity(int severity) {
		this.severity = severity;
	}

	private String status;
	private String trend;
	private String occurTime;
	private String lastTime;
	private String opStatus;
	private String detail;
	private String originSn;
	private String originInfo;
	private Integer upgradeCount;
	private Boolean originSeverity;
	private String clearTime;
	private String confirmTime;
	private String confirmUserId;
	private String delTime;
	private String delUserId;
	private String relatedKpi;
	private Integer relatedMosn;
	private String dataTime;
	private String dataValue;
	private String moip;
	private String moalias;
	private String causeAlias;
	private int health;
	private Character isNotify;
	private String almLocator;
	private byte flag;

	public Alarm() {
	}

	/**
	 * @return the id
	 */
	public AlarmId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(AlarmId id) {
		this.id = id;
	}

	/**
	 * @return the mosn
	 */
	public int getMosn() {
		return mosn;
	}

	/**
	 * @param mosn the mosn to set
	 */
	public void setMosn(int mosn) {
		this.mosn = mosn;
	}

	

	/**
	 * @return the pmosn
	 */
	public int getPmosn() {
		return pmosn;
	}

	/**
	 * @param pmosn the pmosn to set
	 */
	public void setPmosn(int pmosn) {
		this.pmosn = pmosn;
	}

	/**
	 * @return the motype
	 */
	public String getMotype() {
		return motype;
	}

	/**
	 * @param motype the motype to set
	 */
	public void setMotype(String motype) {
		this.motype = motype;
		this.topMoType = motype.substring(0, motype.length()>=4?4:motype.length());
	}

	private String topMoType;
	/**
	 * @return the topMoType
	 */
	public String getTopMoType() {
		return topMoType;
	}

	/**
	 * @param topMoType the topMoType to set
	 */
	public void setTopMoType(String topMoType) {
		this.topMoType = topMoType;
	}

	/**
	 * @return the alarmKpi
	 */
	public String getAlarmKpi() {
		return alarmKpi;
	}

	/**
	 * @param alarmKpi the alarmKpi to set
	 */
	public void setAlarmKpi(String alarmKpi) {
		this.alarmKpi = alarmKpi;
	}

	/**
	 * @return the cause
	 */
	public String getCause() {
		return cause;
	}

	/**
	 * @param cause the cause to set
	 */
	public void setCause(String cause) {
		this.cause = cause;
	}

	/**
	 * @return the almType
	 */
	public String getAlmType() {
		return almType;
	}

	/**
	 * @param almType the almType to set
	 */
	public void setAlmType(String almType) {
		this.almType = almType;
	}

	/**
	 * @return the suppressed
	 */
	public Character getSuppressed() {
		return suppressed;
	}

	/**
	 * @param suppressed the suppressed to set
	 */
	public void setSuppressed(Character suppressed) {
		this.suppressed = suppressed;
	}

	/**
	 * @return the addInfo
	 */
	public String getAddInfo() {
		return addInfo;
	}

	/**
	 * @param addInfo the addInfo to set
	 */
	public void setAddInfo(String addInfo) {
		this.addInfo = addInfo;
	}


	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the trend
	 */
	public String getTrend() {
		return trend;
	}

	/**
	 * @param trend the trend to set
	 */
	public void setTrend(String trend) {
		this.trend = trend;
	}

	/**
	 * @return the occurTime
	 */
	public String getOccurTime() {
		return occurTime;
	}

	/**
	 * @param occurTime the occurTime to set
	 */
	public void setOccurTime(String occurTime) {
		this.occurTime = occurTime;
	}

	/**
	 * @return the lastTime
	 */
	public String getLastTime() {
		return lastTime;
	}

	/**
	 * @param lastTime the lastTime to set
	 */
	public void setLastTime(String lastTime) {
		this.lastTime = lastTime;
	}

	/**
	 * @return the opStatus
	 */
	public String getOpStatus() {
		return opStatus;
	}

	/**
	 * @param opStatus the opStatus to set
	 */
	public void setOpStatus(String opStatus) {
		this.opStatus = opStatus;
	}

	/**
	 * @return the detail
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * @param detail the detail to set
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * @return the originSn
	 */
	public String getOriginSn() {
		return originSn;
	}

	/**
	 * @param originSn the originSn to set
	 */
	public void setOriginSn(String originSn) {
		this.originSn = originSn;
	}

	/**
	 * @return the originInfo
	 */
	public String getOriginInfo() {
		return originInfo;
	}

	/**
	 * @param originInfo the originInfo to set
	 */
	public void setOriginInfo(String originInfo) {
		this.originInfo = originInfo;
	}

	/**
	 * @return the upgradeCount
	 */
	public Integer getUpgradeCount() {
		return upgradeCount;
	}

	/**
	 * @param upgradeCount the upgradeCount to set
	 */
	public void setUpgradeCount(Integer upgradeCount) {
		this.upgradeCount = upgradeCount;
	}

	/**
	 * @return the originSeverity
	 */
	public Boolean getOriginSeverity() {
		return originSeverity;
	}

	/**
	 * @param originSeverity the originSeverity to set
	 */
	public void setOriginSeverity(Boolean originSeverity) {
		this.originSeverity = originSeverity;
	}

	/**
	 * @return the clearTime
	 */
	public String getClearTime() {
		return clearTime;
	}

	/**
	 * @param clearTime the clearTime to set
	 */
	public void setClearTime(String clearTime) {
		this.clearTime = clearTime;
	}

	/**
	 * @return the confirmTime
	 */
	public String getConfirmTime() {
		return confirmTime;
	}

	/**
	 * @param confirmTime the confirmTime to set
	 */
	public void setConfirmTime(String confirmTime) {
		this.confirmTime = confirmTime;
	}

	/**
	 * @return the confirmUserId
	 */
	public String getConfirmUserId() {
		return confirmUserId;
	}

	/**
	 * @param confirmUserId the confirmUserId to set
	 */
	public void setConfirmUserId(String confirmUserId) {
		this.confirmUserId = confirmUserId;
	}

	/**
	 * @return the delTime
	 */
	public String getDelTime() {
		return delTime;
	}

	/**
	 * @param delTime the delTime to set
	 */
	public void setDelTime(String delTime) {
		this.delTime = delTime;
	}

	/**
	 * @return the delUserId
	 */
	public String getDelUserId() {
		return delUserId;
	}

	/**
	 * @param delUserId the delUserId to set
	 */
	public void setDelUserId(String delUserId) {
		this.delUserId = delUserId;
	}

	/**
	 * @return the relatedKpi
	 */
	public String getRelatedKpi() {
		return relatedKpi;
	}

	/**
	 * @param relatedKpi the relatedKpi to set
	 */
	public void setRelatedKpi(String relatedKpi) {
		this.relatedKpi = relatedKpi;
	}

	/**
	 * @return the relatedMosn
	 */
	public Integer getRelatedMosn() {
		return relatedMosn;
	}

	/**
	 * @param relatedMosn the relatedMosn to set
	 */
	public void setRelatedMosn(Integer relatedMosn) {
		this.relatedMosn = relatedMosn;
	}

	/**
	 * @return the dataTime
	 */
	public String getDataTime() {
		return dataTime;
	}

	/**
	 * @param dataTime the dataTime to set
	 */
	public void setDataTime(String dataTime) {
		this.dataTime = dataTime;
	}

	/**
	 * @return the dataValue
	 */
	public String getDataValue() {
		return dataValue;
	}

	/**
	 * @param dataValue the dataValue to set
	 */
	public void setDataValue(String dataValue) {
		this.dataValue = dataValue;
	}

	/**
	 * @return the moip
	 */
	public String getMoip() {
		return moip;
	}

	/**
	 * @param moip the moip to set
	 */
	public void setMoip(String moip) {
		this.moip = moip;
	}

	/**
	 * @return the moalias
	 */
	public String getMoalias() {
		return moalias;
	}

	/**
	 * @param moalias the moalias to set
	 */
	public void setMoalias(String moalias) {
		this.moalias = moalias;
	}

	/**
	 * @return the causeAlias
	 */
	public String getCauseAlias() {
		return causeAlias;
	}

	/**
	 * @param causeAlias the causeAlias to set
	 */
	public void setCauseAlias(String causeAlias) {
		this.causeAlias = causeAlias;
	}

	/**
	 * @return the health
	 */
	public int getHealth() {
		return health;
	}

	/**
	 * @param health the health to set
	 */
	public void setHealth(int health) {
		this.health = health;
	}

	/**
	 * @return the isNotify
	 */
	public Character getIsNotify() {
		return isNotify;
	}

	/**
	 * @param isNotify the isNotify to set
	 */
	public void setIsNotify(Character isNotify) {
		this.isNotify = isNotify;
	}

	/**
	 * @return the almLocator
	 */
	public String getAlmLocator() {
		return almLocator;
	}

	/**
	 * @param almLocator the almLocator to set
	 */
	public void setAlmLocator(String almLocator) {
		this.almLocator = almLocator;
	}

	/**
	 * @return the flag
	 */
	public byte getFlag() {
		return flag;
	}

	/**
	 * @param flag the flag to set
	 */
	public void setFlag(byte flag) {
		this.flag = flag;
	}

	private String causeWithSeverity;
	/**
	 * @return the causeWithSeverity
	 */
	public String getCauseWithSeverity() {
		return causeWithSeverity;
	}

	/**
	 * @param causeWithSeverity the causeWithSeverity to set
	 */
	public void setCauseWithSeverity(String causeWithSeverity) {
		this.causeWithSeverity = causeWithSeverity;
	}
	
}
